server:
  servlet:
    encoding:
      enabled: true # Включить ли поддержку кодирования HTTP.
      charset: UTF-8 # Кодировка HTTP запросов и ответов. Добавляется в заголовок «Content-Type», если не указано явно.
      force: true # Принудительно использовать кодировку для настроенной кодировки в HTTP запросах и ответах.

yandex:
  geo-apikey: 111111111111111111111111111111111111
  max-batch-size: 100

spring:
  jackson:
    time: Europe/Moscow
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: '@activatedProperties@'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: false
  liquibase:
    enabled: true
logging:
  file:
    name: logs/geolocation.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
  level:
    root: INFO
